### ISSUE TITLE
Issue with rules applying to players who did not read the documentation

### ISSUE THREAD

**Issue by AGTRyanGeorge** [jasonwist/Just_a_Few_Garys#2]
We have noticed that there have been some inconsistencies with the rules being applied to all players equally. One of the biggest factors has been `Section 7.01 - 2017 Amendments` where there was a request to change waiver bids to $1, up from $0, with the resulting penalty being that a player must bench their kicker if they put a waiver in for $0. This rule was agreed upon, but unfortunately it is still being applied to players who have not read the rule.

Steps to reproduce:
1. Waiver a player for $0

**Comment by jasonwist** [comment]
Hi,

Thank you for the Issue. It should be fixed.
